"""

The following is the first .py file that reads the LANGEVIN_DATA.txt file and then adds the columns' headers.
It also indicates the index column as 'Time' column and then saves the dataset in data.txt file.

"""

import pandas as pd

df = pd.read_csv("LANGEVIN_DATA.txt", delim_whitespace=True, nrows=100000)

df.columns = ['Time',
              'Occupant Number',
              'Occupancy 1',
              'Occupancy 2',
              'Survey Time',
              'INDOOR Ambient Temp.',
              'INDOOR Relative Humidity',
              'INDOOR Air Velocity',
              'INDOOR Mean Radiant Temp.',
              'INDOOR Lumens',
              'INDOOR CO2',
              'OUTDOOR Ambient Temp.',
              'OUTDOOR Relative Humidity',
              'OUTDOOR Air Velocity',
              'Metabolic Rate (last 15 mins.)',
              'Metabolic Rate (last 1 hour)',
              'Clothing Level',
              'Clothing Level (+ Chair)',
              'Min. Accept. Sensation (right now)',
              'Med. Accept. Sensation (right now)',
              'Max. Accept. Sensation (right now)',
              'Min. Accept (seasonal median)',
              'Med. Accept (seasonal median)',
              'Max. Accept (seasonal median)',
              'Thermal Preference (right now)',
              'Gender',
              'Age',
              'Office Type',
              'Floor Number',
              'Location on Floor Plan',
              'Min. Accept. Sensation (summer)',
              'Min. Accept. Sensation (winter)',
              'Med. Accept. Sensation (summer)',
              'Med. Accept. Sensation (winter)',
              'Max. Accept. Sensation (summer)',
              'Max. Accept. Sensation (winter)',
              'General Thermal Comfort (right now)',
              'Thermal Comfort Movement (recently)',
              'Discomfort Location: HEAD',
              'Discomfort Location: CHEST',
              'Discomfort Location: BACK',
              'Discomfort Location: PELVIS',
              'Discomfort Location: ARMS',
              'Discomfort Location: HANDS',
              'Discomfort Location: LEGS',
              'Discomfort Location: FEET',
              'Discomfort Location: ALL OVER',
              'Thermal Sensation (right now)',
              'Thermal Sensation Movement (recently)',
              'Relative "Busyness" (recently)',
              'Relative Productivity (recently)',
              'General Satisfaction w/ Amount of Space',
              'General Satisfaction w/ Privacy',
              'General Thermal Comfort',
              'General Satisfaction w/ Perceived Control',
              'Fan/Heater Class',
              'State of Fan/Heater',
              'State of Window',
              'Current Thermostat COOLING Setpoint',
              'Base Thermostat COOLING Setpoint',
              'Current Thermostat HEATING Setpoint',
              'Base Thermostat HEATING Setpoint',
              'Clothing Change (recently)',
              'Clothing Change UP (recently)',
              'Clothing Change DOWN (recently)',
              'Net Clothing Change (recently)',
              'Drinking Beverage?',
              'Purpose of getting COLD drink',
              'Purpose of getting WARM drink',
              'Action on WINDOW (recently)',
              'WINDOW state (right now)',
              'How long ago was WINDOW action?',
              'Action on DOOR (recently)',
              'DOOR state (right now)',
              'How long ago was DOOR action?',
              'Action on BLINDS (recently)',
              'BLINDS state (right now)',
              'How long ago was BLINDS action?',
              'Action on LOCAL FAN (recently)',
              'LOCAL FAN state (right now)',
              'How long ago was LOCAL FAN action?',
              'Action on LOCAL HEATER (recently)',
              'LOCAL HEATER state (right now)',
              'How long ago was LOCAL HEATER action?',
              'Action on THERMOSTAT (recently)',
              'THERMOSTAT state (right now)',
              'How long ago was THERMOSTAT action?',
              'Reason for no WINDOW action',
              'Reason for no DOOR action',
              'Reason for no BLINDS action',
              'Reason for no LOCAL FAN action',
              'Reason for no LOCAL HEATER action',
              'Reason for no THERMOSTAT action',
              'CLOTHING availability',
              'DRINKS availability',
              'LOCAL HEATER availability',
              'LOCAL FAN availability',
              'THERMOSTAT availability',
              'WINDOW availability',
              'DOOR availability',
              'BLINDS availability',
              'CLOTHING effectiveness',
              'DRINKS effectiveness',
              'LOCAL HEATER effectiveness',
              'LOCAL FAN effectiveness',
              'THERMOSTAT effectiveness',
              'WINDOW effectiveness',
              'DOOR effectiveness',
              'BLINDS effectiveness',
              'Reported Discomfort to Management',
              'Chooses set point that maximizes PRODUCTIVITY',
              'Chooses set point that maximized COMFORT/PLEASURE',
              'Wishes set point to stay at setting they choose',
              'Chooses set point that is most agreeable to OTHERS',
              'Chooses set point that is most ENERGY EFFICIENT',
              'Chooses set point most in line with MGMT policies',
              'Choooses set point most TYPICAL of office setting',
              'Predicted Mean Vote (PMV)']

df.set_index('Time', inplace=True)

df.to_csv('data.txt', index=True)
